services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    plan: free
